version: '3.8'
services:
  web:
    build: 
        context: .
        dockerfile: ./dev/Dockerfile
    container_name:  cms-cont
    env_file:
      - ./dev/.env.dev
    command: sh -c "python myproject/manage.py collectstatic --noinput &&
             python myproject/manage.py makemigrations &&
             python myproject/manage.py migrate &&
             source dev/create_superuser_dev.sh && 
             python myproject/manage.py runserver 0.0.0.0:8000"
    ports:
          - "8000:8000"
    volumes:
      - ./myproject:/app/myproject
    depends_on:
      -  db

  db:
    image: postgres:13.0-alpine
    container_name:  postgres-cont
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: